# Generated by Django 4.2.2 on 2023-06-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('userId', models.CharField(max_length=30)),
                ('userPw', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
