# Generated by Django 4.2.2 on 2023-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIdx', models.IntegerField(unique=1)),
                ('lastTime', models.TimeField()),
            ],
            options={
                'db_table': 'last_time',
            },
        ),
    ]
